### ISSUE TITLE
Not available for R version 3.6.2 Patched

### ISSUE THREAD

**Issue by GregChojecki** [guillaumehans/RNIR#1]
Hi there,

I am not sure why, but while trying to install it I get the message:

Installing package into ‘C:/Users/Test/Documents/r/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘RNIR’ is not available (for R version 3.6.2 Patched)

Any suggestions, please?

Cheers,
Greg

**Comment by guifh** [comment]
RNIR is not a package, there is nothing to install.
